language: android
android:
   components:
   - tools
   - platform-tools
   - android-23
   - build-tools-23.0.2
   - extra
   
env:
  global:
    MALLOC_ARENA_MAX=1
   
jdk: oraclejdk7

sudo: false

notifications:
  email: false

script:
  - ulimit -s 1082768
  - rm settings.gradle
  - mv travis.gradle settings.gradle
  - sed -i -e "s/apl'/apl_clone'/g" app/build.gradle
  - touch app/extra.gradle
  - printf 'GooglePlayLicenseKey="GooglePlayLicenseKey"\nIapProductKey="IapProductKey"\ncc="cc"\nii="ii"' > app/keys.properties
  - MALLOC_ARENA_MAX=1
  - chmod a+x gradlew
  - ./gradlew clean assembleTravisDebug --stacktrace
